//폰트 추가
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AccessLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="flex items-center justify-center pt-8">
      <div className="w-[650px] h-[705px] bg-white rounded-[40px] shadow-[0px_0px_20px_0px_rgba(0,0,0,0.25)]">
        <main>{children}</main>
      </div>
    </div>
  );
}
