import type { Metadata } from "next";
import HomeBtn from "./components/HomeBtn";
import { COLORS, FONT_SIZE, FONT_WEIGHT } from "@/styles/theme/tokens";
import Dropdown from "../components/Dropdown";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface HistoryProps {
  children: React.ReactNode;
  label: string;
}

export default function HistoryLayout({ children, label }: HistoryProps) {
  return (
    <div className="relative w-full h-screen overflow-auto px-13 py-7">
      <HomeBtn />
      <div className="flex flex-col items-stretch w-[950px] pt-10 px-12">
        <div
          className="flex"
          style={{
            fontSize: FONT_SIZE.headline,
            fontWeight: FONT_WEIGHT.headline,
          }}
        >
          <span style={{ color: COLORS.primary.mint }}>🗂️MON</span>
          <span style={{ color: COLORS.primary.navy }}>{label} 히스토리</span>
        </div>
        <div className="flex gap-4.5">
          <Dropdown type="day" />
          <Dropdown type="category" />
          <Dropdown type="result" />
        </div>
      </div>
      <main>{children}</main>
    </div>
  );
}
