import type { Metadata } from "next";
import HomeBtn from "./components/HomeBtn";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HistoryLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="relative w-full h-screen overflow-auto px-13 py-5">
      <HomeBtn />
      <main>{children}</main>
    </div>
  );
}
