import type { Metadata } from "next";
import "@/styles/globals.css";
import { SHADOW } from "@/styles/theme/tokens";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AccountLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="flex items-center justify-center pt-8">
      <div className="w-[650px] h-[705px] bg-white rounded-[40px]" style={{ boxShadow: SHADOW.interactive }}>
        <main>{children}</main>
      </div>
    </div>
  );
}
