import type { Metadata } from "next";
import "@/styles/globals.css";
import { SHADOW } from "@/styles/theme/tokens";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AccountLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="justify-items-center pt-8">
      <div
        style={{
          width: "630px",
          height: "710px",
          textAlign: "center",
          backgroundColor: "white",
          boxShadow: SHADOW.interactive,
          borderRadius: "40px",
        }}
      >
        <main>{children}</main>
      </div>
    </div>
  );
}
